version: '3'
services:

  #Flask Service
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaskapp:0.1
    container_name: flaskapp
    restart: unless-stopped
    tty: true
    environment:
      FLASK_APP: project
      FLASK_DEBUG: 1
    env_file:
      - .env.credentials
    ports:
      - 80:5000
      - 443:443
